// ========================================
// English translations (default)
// ========================================

import type { TranslationDict } from "./index.ts";

export const en: TranslationDict = {
  // ── Header / Footer ──
  "header.subtitle": "Subscription Health",
  "header.report_by": "Report by rc-insights",
  "header.subscription_health_report": "Subscription Health Report",
  "header.generated": "Generated",
  "footer.generated_by": "Generated by rc-insights — AI-powered subscription health analysis",
  "footer.generated_by_html": "Generated by <a href=\"https://github.com/nicething/rc-insights\">rc-insights</a> — an AI-powered tool for RevenueCat Charts API",

  // ── Section Titles ──
  "section.overview": "Overview (Last 28 days)",
  "section.overview_md": "Overview",
  "section.health_score_chart": "Health Score Chart",
  "section.metrics_overview": "Metrics Overview",
  "section.anomalies": "Anomalies Detected",
  "section.recommendations": "Key Insights & Recommendations",
  "section.recommendations_md": "Recommendations",
  "section.crystal_ball": "Crystal Ball",
  "section.strategy": "Strategy",
  "section.strategy_analysis": "Strategy Analysis",
  "section.next_product_ideas": "Next Product Ideas",
  "section.agent_plan": "AI Agent Action Plan",
  "section.benchmarks": "SOSA 2026 Benchmarks",
  "section.benchmark_reference": "Benchmark Reference",

  // ── Trend Labels ──
  "trend.growing": "Growing",
  "trend.stable": "Stable",
  "trend.declining": "Declining",
  "trend.unknown": "Unknown",

  // ── Trend Labels (with icons, for markdown) ──
  "trend.growing_icon": "📈 Growing",
  "trend.stable_icon": "➡️ Stable",
  "trend.declining_icon": "📉 Declining",

  // ── Status Labels ──
  "status.healthy": "Healthy",
  "status.attention": "Attention",
  "status.critical": "Critical",

  // ── Impact Labels ──
  "impact.high": "HIGH",
  "impact.medium": "MEDIUM",
  "impact.low": "LOW",

  // ── Table Headers ──
  "table.metric": "Metric",
  "table.value": "Value",
  "table.status": "Status",
  "table.trend": "Trend",
  "table.mom_change": "MoM Change",
  "table.benchmark": "Benchmark",
  "table.date": "Date",
  "table.ratio": "Ratio",
  "table.inflow": "Inflow",
  "table.outflow": "Outflow",
  "table.factor": "Factor",
  "table.raw_value": "Raw Value",
  "table.score": "Score",
  "table.weight": "Weight",
  "table.weighted": "Weighted",
  "table.month": "Month",
  "table.base": "Base",
  "table.optimistic": "Optimistic",
  "table.pessimistic": "Pessimistic",
  "table.scenario": "Scenario",
  "table.description": "Description",
  "table.mrr_12m": "+MRR@12m",
  "table.delta_pct": "Delta%",
  "table.keyword": "Keyword",
  "table.trials": "Trials",
  "table.revenue": "Revenue",
  "table.conversion": "Conversion",
  "table.efficiency": "Efficiency",
  "table.offering": "Offering",
  "table.name": "Name",
  "table.performance": "Performance",
  "table.median": "Median",
  "table.top_25": "Top 25%",
  "table.bottom_25": "Bottom 25%",
  "table.action_id": "#",
  "table.action": "Action",
  "table.mcp_tool": "MCP Tool",
  "table.priority": "Priority",
  "table.expected_impact": "Expected Impact",
  "table.12m_impact": "12-Month Impact",
  "table.pct_change": "% Change",

  // ── Metric Display Names ──
  "metric.mrr": "MRR",
  "metric.arr": "ARR",
  "metric.churn": "Churn Rate",
  "metric.trial_conversion_rate": "Trial → Paid",
  "metric.revenue": "Revenue",
  "metric.actives": "Active Subscribers",
  "metric.customers_new": "New Customers",
  "metric.trials_new": "New Trials",
  "metric.refund_rate": "Refund Rate",
  "metric.ltv_per_customer": "LTV per Customer",

  // ── Quick Ratio ──
  "qr.title": "Quick Ratio",
  "qr.grade.excellent": "Excellent",
  "qr.grade.healthy": "Healthy",
  "qr.grade.concerning": "Concerning",
  "qr.grade.leaking": "Leaking",
  // with icons (for markdown)
  "qr.grade.excellent_icon": "🟢 Excellent",
  "qr.grade.healthy_icon": "🟢 Healthy",
  "qr.grade.concerning_icon": "🟡 Concerning",
  "qr.grade.leaking_icon": "🔴 Leaking",

  // ── PMF Score ──
  "pmf.title": "PMF Score",
  "pmf.grade.strong": "Strong PMF",
  "pmf.grade.approaching": "Approaching PMF",
  "pmf.grade.pre": "Pre-PMF",
  "pmf.grade.no_signal": "No PMF Signal",
  // with icons (for markdown)
  "pmf.grade.strong_icon": "🟢 Strong PMF",
  "pmf.grade.approaching_icon": "🟢 Approaching PMF",
  "pmf.grade.pre_icon": "🟡 Pre-PMF",
  "pmf.grade.no_signal_icon": "🔴 No PMF Signal",
  "pmf.diagnosis_label": "Diagnosis",
  "pmf.verdict_label": "Verdict",
  "pmf.decision_label": "Decision",
  "pmf.reasoning_label": "Reasoning",

  // ── MRR Forecast ──
  "forecast.title": "MRR Forecast",

  // ── Scenarios ──
  "scenario.title": "What-if Scenarios",
  "scenario.best": "Best Scenario",
  "scenario.best_scenario": "Best scenario",
  "scenario.vs_baseline": "vs baseline at 12mo",

  // ── Strategy ──
  "strategy.keyword_analysis": "Keyword Analysis",
  "strategy.keyword_attribution": "Keyword Attribution",
  "strategy.offering_analysis": "Offering Analysis",
  "strategy.offering_performance": "Offering Performance",

  // ── Anomalies ──
  "anomaly.none": "No anomalies detected in the analyzed period.",
  "anomaly.on": "on",

  // ── Recommendations ──
  "rec.related": "Related",
  "rec.impact": "Impact",
  "rec.related_metric": "Related Metric",

  // ── Next Product Ideas ──
  "product.complexity": "Complexity",
  "product.source": "Source",
  "product.evidence": "Evidence",
  "product.direction.vertical": "↕️ Up/Down the Value Chain",
  "product.direction.horizontal": "↔️ Expand Sideways",
  "product.direction.adjacent": "🔀 Jump to New Market",

  // ── Agent Plan ──
  "agent.estimated_impact": "Estimated Impact",
  "agent.estimated_total_impact": "Estimated Total Impact",

  // ── Benchmark Reference ──
  "benchmark.description": "Based on RevenueCat's **State of Subscription Apps 2026** (SOSA 2026):",
  "benchmark.trial_conversion": "Trial Conversion",
  "benchmark.monthly_churn": "Monthly Churn",
  "benchmark.refund_rate": "Refund Rate",
  "benchmark.mrr": "MRR",
  "benchmark.ltv_per_customer": "LTV per Customer",

  // ── Misc ──
  "misc.benchmark_label": "benchmark",
  "misc.mom": "MoM",
  "misc.na": "N/A",
};
