// ========================================
// Markdown 報告產生器
// 產生可直接分享的 .md 檔案
// ========================================

import type { HealthReport, MetricHealth, Recommendation, Anomaly } from "../api/types.ts";
import { formatCurrency, formatPercent, formatNumber, formatChange } from "../utils/formatting.ts";

/** 健康狀態圖示 */
const STATUS_ICON: Record<string, string> = {
  green: "🟢",
  yellow: "🟡",
  red: "🔴",
};

/** 趨勢方向文字 */
const TREND_LABEL: Record<string, string> = {
  growing: "📈 Growing",
  stable: "➡️ Stable",
  declining: "📉 Declining",
};

/** 指標顯示名稱 */
const DISPLAY_NAMES: Record<string, string> = {
  mrr: "MRR",
  arr: "ARR",
  churn: "Churn Rate",
  trial_conversion_rate: "Trial → Paid",
  revenue: "Revenue",
  actives: "Active Subscribers",
  customers_new: "New Customers",
  trials_new: "New Trials",
  refund_rate: "Refund Rate",
  ltv_per_customer: "LTV per Customer",
};

/**
 * 根據單位格式化數值
 */
function formatValue(value: number, unit: string): string {
  switch (unit) {
    case "$":
      return formatCurrency(value);
    case "%":
      return formatPercent(value);
    case "#":
      return formatNumber(value);
    default:
      return value.toLocaleString("en-US");
  }
}

/**
 * 產生 Markdown 報告
 * @param report - 健康報告資料
 * @returns Markdown 字串
 */
export function renderMarkdownReport(report: HealthReport): string {
  const lines: string[] = [];

  // 標題
  lines.push(`# 📊 ${report.projectName} — Subscription Health Report`);
  lines.push("");
  lines.push(`> Generated by **rc-insights** on ${new Date(report.generatedAt).toLocaleString()}`);
  lines.push("");

  // 概覽表格
  lines.push("## Overview");
  lines.push("");
  lines.push("| Metric | Value | Status | Trend | MoM Change | Benchmark |");
  lines.push("|--------|------:|:------:|-------|------------|-----------|");

  // 排序：紅色優先
  const statusOrder: Record<string, number> = { red: 0, yellow: 1, green: 2 };
  const sorted = [...report.metrics].sort(
    (a, b) => (statusOrder[a.status] ?? 1) - (statusOrder[b.status] ?? 1),
  );

  for (const metric of sorted) {
    const name = DISPLAY_NAMES[metric.name] ?? metric.name;
    const value = formatValue(metric.value, metric.unit);
    const icon = STATUS_ICON[metric.status] ?? "⚪";
    const trend = TREND_LABEL[metric.trend] ?? "Unknown";
    const change = metric.changePercent !== 0 ? formatChange(metric.changePercent) : "—";
    const benchmark = metric.benchmark > 0 ? formatValue(metric.benchmark, metric.unit) : "—";

    lines.push(`| ${name} | ${value} | ${icon} | ${trend} | ${change} | ${benchmark} |`);
  }

  lines.push("");

  // 異常偵測
  if (report.anomalies.length > 0) {
    lines.push("## ⚠️ Anomalies Detected");
    lines.push("");

    for (const anomaly of report.anomalies) {
      const icon = anomaly.type === "spike" ? "⚡" : "📉";
      lines.push(
        `- ${icon} **${anomaly.metric}**: ${anomaly.type === "spike" ? "+" : "-"}${anomaly.magnitude.toFixed(1)}% on ${anomaly.date} — ${anomaly.description}`,
      );
    }

    lines.push("");
  }

  // 建議
  if (report.recommendations.length > 0) {
    lines.push("## 💡 Recommendations");
    lines.push("");

    for (let i = 0; i < report.recommendations.length; i++) {
      const rec = report.recommendations[i]!;
      const impactBadge =
        rec.impact === "high"
          ? "🔴 HIGH"
          : rec.impact === "medium"
            ? "🟡 MEDIUM"
            : "🟢 LOW";

      lines.push(`### ${i + 1}. ${rec.title}`);
      lines.push("");
      lines.push(`**Impact:** ${impactBadge} | **Related Metric:** ${DISPLAY_NAMES[rec.relatedMetric] ?? rec.relatedMetric}`);
      lines.push("");
      lines.push(rec.description);
      lines.push("");
    }
  }

  // 基準參考
  lines.push("## 📏 Benchmark Reference");
  lines.push("");
  lines.push("Based on RevenueCat's **State of Subscription Apps 2026** (SOSA 2026):");
  lines.push("");
  lines.push("| Metric | Median | Top 25% | Bottom 25% |");
  lines.push("|--------|-------:|--------:|-----------:|");
  lines.push("| Trial Conversion | 35% | 55% | 20% |");
  lines.push("| Monthly Churn | 6% | 3.5% | 8% |");
  lines.push("| Refund Rate | 3% | 1.5% | 5% |");
  lines.push("| MRR | $2,000 | $10,000 | $500 |");
  lines.push("");

  // 底部
  lines.push("---");
  lines.push("");
  lines.push("*Generated by [rc-insights](https://github.com/nicething/rc-insights) — an AI-powered subscription health analysis tool for RevenueCat.*");
  lines.push("");

  return lines.join("\n");
}
